In [1]:

import os
from enum import Enum

import ms3
import pandas as pd

from code.utils import make_pitch_array, prepare_labels, make_labeled_pitch_array

DLC_PATH = ms3.resolve_dir("~/distant_listening_corpus")

In [2]:
def filter_corpus(corpus):
    corpus.view.include("facets", "scores")#, "expanded")
    #corpus.disambiguate_facet("expanded")
    corpus.disambiguate_facet("scores")
    corpus.view.pieces_with_incomplete_facets = False
    
def get_ms3_corpus(corpus_path):
    corpus = ms3.Corpus(corpus_path)
    filter_corpus(corpus)
    return corpus

for subcorpus_dir in os.listdir(DLC_PATH):
    subcorpus_path = os.path.join(DLC_PATH, subcorpus_dir)
    if os.path.isfile(subcorpus_path): continue
    corpus = get_ms3_corpus(subcorpus_path)
    break
    
corpus

[default|all]
Corpus 'kozeluh_sonatas'
------------------------
Location: /home/laser/distant_listening_corpus/kozeluh_sonatas
View: This view is called 'default'. It
	- excludes pieces that are not contained in the metadata,
	- filters out file extensions requiring conversion (such as .xml),
	- excludes review files and folders,
	- includes only facets containing 'scores', and
	- excludes pieces that do not have at least one file per selected facet (scores).

All 49 pieces are listed in 'metadata.tsv':

             scores
           detected
09op08no1a        1
09op08no1b        1
10op08no2a        1
10op08no2b        1
10op08no2c        1
11op10no1a        1
14op13no2a        1
14op13no2b        1
14op13no2c        1
15op13no3a        1
15op13no3b        1
15op13no3c        1
16op15no1a        1
16op15no1b        1
16op15no1c        1
17op15no2a        1
17op15no2b        1
17op15no2c        1
19op17no1a        1
19op17no1b        1
19op17no1c        1
20op17no2a        1
20op17no2b        1
20op17no2c        1
21op17no3a        1
21op17no3b        1
22op20no1a        1
22op20no1b        1
22op20no1c        1
23op20no2a        1
23op20no2b        1
23op20no2c        1
24op20no3a        1
24op20no3b        1
24op20no3c        1
25op26no1a        1
25op26no1b        1
25op26no1c        1
26op26no2a        1
26op26no2b        1
27op26no3a        1
27op26no3b        1
27op26no3c        1
28op30no1a        1
28op30no1b        1
28op30no1c        1
29op30no2a        1
29op30no2b        1
29op30no2c        1
11/12 facets are excluded from this view.
245/490 files are excluded from this view.

245 files have been excluded based on their subdir.

In [3]:
corpus = get_ms3_corpus("~/distant_listening_corpus/beethoven_piano_sonatas")

for _, piece in corpus.iter_pieces():
    break
    
for fileinfo, facets in piece.iter_extracted_facets(
        ("measures", "notes", "expanded"),
        force=True,
        unfold=True,
        interval_index=False
):
    break

measures = facets["measures"]
display(measures.head(3))
notes = facets["notes"]
notes.head(3)

,mc,mn,mc_playthrough,mn_playthrough,quarterbeats,duration_qb,keysig,timesig,act_dur,mc_offset,numbering_offset,dont_count,barline,breaks,repeats,next
0,1,0,1,0a,0,1.0,-4,2/2,1/4,3/4,<NA>,1,NaN,NaN,firstMeasure,"(2,)"
1,2,1,2,1a,1,4.0,-4,2/2,1,0,<NA>,<NA>,NaN,NaN,NaN,"(3,)"
2,3,2,3,2a,5,4.0,-4,2/2,1,0,<NA>,<NA>,NaN,NaN,NaN,"(4,)"

,mc,mn,mc_playthrough,mn_playthrough,quarterbeats_playthrough,quarterbeats_all_endings,duration_qb,mc_onset,mn_onset,timesig,...,duration,gracenote,nominal_duration,scalar,tied,tpc,midi,name,octave,chord_id
0,1,0,1,0a,0,0,1.0,0,3/4,2/2,...,1/4,NaN,1/4,1,<NA>,0,60,C4,4,0
1,2,1,2,1a,1,1,1.0,0,0,2/2,...,1/4,NaN,1/4,1,<NA>,-1,65,F4,4,1
2,2,1,2,1a,2,2,1.0,1/4,1/4,2/2,...,1/4,NaN,1/4,1,<NA>,-4,68,Ab4,4,2

In [4]:
pitch_array = make_pitch_array(notes, measures, label_notes=False)
pitch_array.to_csv("beethoven1.tsv", sep="\t", index=False)
pitch_array

,onset_div,duration_div,pitch,tpc,step,alter,ts_beats,ts_beat_type,staff,voice,is_note_onset,beat,ks_fifths,mc,mn,mc_playthrough,mn_playthrough,quarterbeats_playthrough,duration,octave
0,0,6,60,0,C,0,2,2,1,1,True,2.5,-4,1,0,1,0a,0,1/4,4
1,6,6,65,-1,F,0,2,2,1,1,True,1.0,-4,2,1,2,1a,1,1/4,4
2,12,6,68,-4,A,-1,2,2,1,1,True,1.5,-4,2,1,2,1a,2,1/4,4
3,18,6,72,0,C,0,2,2,1,1,True,2.0,-4,2,1,2,1a,3,1/4,5
4,24,6,77,-1,F,0,2,2,1,1,True,2.5,-4,2,1,2,1a,4,1/4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3381,7278,6,53,-1,F,0,2,2,2,1,True,1.0,-4,154,152,308,152b,1213,1/4,3
3382,7278,6,65,-1,F,0,2,2,1,1,True,1.0,-4,154,152,308,152b,1213,1/4,4
3383,7278,6,68,-4,A,-1,2,2,1,1,True,1.0,-4,154,152,308,152b,1213,1/4,4
3384,7278,6,72,0,C,0,2,2,1,1,True,1.0,-4,154,152,308,152b,1213,1/4,5
3385,7278,6,77,-1,F,0,2,2,1,1,True,1.0,-4,154,152,308,152b,1213,1/4,5

In [5]:
labeled_pitch_array = make_labeled_pitch_array(
    notes=notes, 
    labels=facets["expanded"],
    measures=measures
)

tmp_labeled_pitch_array = labeled_pitch_array[[
    col for col 
    in labeled_pitch_array.columns 
    if col not in pitch_array.columns]]
tmp_labeled_pitch_array = prepare_labels(facets["expanded"])
labeled_pitch_array.to_csv("beethoven1_labeled.tsv", sep="\t", index=False)
labeled_pitch_array

,onset_div,duration_div,pitch,tpc,step,alter,ts_beats,ts_beat_type,staff,voice,...,numeral_or_applied_to_numeral,globalkey_tpc,localkey_tpc,tonicized_tpc,sic_with_global,sic_with_local,sic_with_tonicized,tpc_is_in_label,tpc_is_root,tpc_is_bass
0,0,6,60,0,C,0,2,2,1,1,...,i,-1,-1,-1,1,1,1,True,False,False
1,6,6,65,-1,F,0,2,2,1,1,...,i,-1,-1,-1,0,0,0,True,True,True
2,12,6,68,-4,A,-1,2,2,1,1,...,i,-1,-1,-1,-3,-3,-3,True,False,False
3,18,6,72,0,C,0,2,2,1,1,...,i,-1,-1,-1,1,1,1,True,False,False
4,24,6,77,-1,F,0,2,2,1,1,...,i,-1,-1,-1,0,0,0,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3381,7278,6,53,-1,F,0,2,2,2,1,...,i,-1,-1,-1,0,0,0,True,True,True
3382,7278,6,65,-1,F,0,2,2,1,1,...,i,-1,-1,-1,0,0,0,True,True,True
3383,7278,6,68,-4,A,-1,2,2,1,1,...,i,-1,-1,-1,-3,-3,-3,True,False,False
3384,7278,6,72,0,C,0,2,2,1,1,...,i,-1,-1,-1,1,1,1,True,False,False
3385,7278,6,77,-1,F,0,2,2,1,1,...,i,-1,-1,-1,0,0,0,True,True,True

In [6]:
class Purpose(str, Enum):
    """Vocabulary defining what individual fields (columns) are used for.
    Description strings X fit gramatically as in "used for X"."""
    auxiliary = "computing fields"
    input = "input graph creation"
    metadata = "input graph metadata and informational purposes"
    beat_inference = "training beat inference task"
    cadence_induction = "training cadence induction task"
    harmony_inference = "training harmony inference task"
    phrase_inference = "training phrase inference task"
    section_inference = "training section inference task"
    # none = unused columns should not be included in the specs


tpc_description = "Tonal Pitch Class (0=C, -1=F, 1=G, etc., aka specific pitch, aka fifths)"
spec_specs = dict(
    onset_div = dict(
        description = "Proportional integer position",
        used_for = Purpose.input,
        ),
    duration_div = dict(
        description = "Proportional integer duration",
        used_for = Purpose.input,
        ),
    pitch = dict(
        description = "MIDI value",
        used_for = Purpose.input,
        ),
    tpc = dict(
        description = tpc_description,
        used_for = Purpose.auxiliary,
        ),
    step = dict(
        description = "Note name without accidental (A-G)",
        used_for = Purpose.input,
        ),
    alter = dict(
        description = "Note accidental: [-3, 3]",
        used_for = Purpose.input,
        ),
    ts_beats = dict(
        description = "Numerator of the time signature",
        used_for = Purpose.input,
        ),
    ts_beat_type = dict(
        description = "Denominator of the time signature",
        used_for = Purpose.input,
        ),
    staff = dict(
        description = "Number of the staff containing the note, 1 being the upper staff",
        used_for = Purpose.input,
        ),
    voice = dict(
        description = "Notational layer containing the note: [1, 4]",
        used_for = Purpose.input,
        ),
    is_note_onset = dict(
        description = "False when a note is tied to a previous one",
        used_for = Purpose.input,
        ),
    beat = dict(
        description = "Values >= 1. Natural numbers represent beat positions according to the time signature. "
                      "The number of beats in a measure is defined by ts_beats but divided by 3 if it's a multiple of 3.",
        used_for = Purpose.beat_inference,
        ),
    ks_fifths = dict(
        description = "Key signature: [-7, 7]",
        used_for = Purpose.input,
        ),
    mc = dict(
        description = "Measure count, ID of the measure-like object (non-unique in unfolded score)",
        used_for = Purpose.metadata,
        ),
    mn = dict(
        description = "Measure number as per conventions. One MN can be composed of several MC.",
        used_for = Purpose.metadata,
        ),
    mc_playthrough = dict(
        description = "Measure count, unique in unfolded score",
        used_for = Purpose.metadata,
        ),
    mn_playthrough = dict(
        description = "Conventional measure numbers but for unfolded score (means of identifying complete measures)",
        used_for = Purpose.input,
        ),
    quarterbeats_playthrough = dict(
        description = "Continuous offset (\"qstamp\") in unfolded score",
        used_for = Purpose.input,
        ),
    duration = dict(
        description = "Note duration expressed as fraction of a whole note",
        used_for = Purpose.auxiliary,
        ),
    section_start = dict(
        description = "True for notes on the first position following a double/repeat bar line or section break. "
                      "True values always correspond to the beginning of an MC, so a section beginning with a rest "
                      "will not be taken into account.",
        used_for = Purpose.section_inference,
    ),
    octave = dict(
        description = "Octave of the note with 4 = middle octave. Does not always correspond to pitch // 12 - 1.",
        used_for = Purpose.metadata,
    ),
    is_harmony_onset = dict(
        description = "True for notes coinciding with a change in harmony.",
        used_for = Purpose.harmony_inference,
    ),
    cadence = dict(
        description = "Original cadence label (my include cadence subtypes)",
        used_for = Purpose.auxiliary,
    ),
    cadence_type = dict(
        description = "Cadence label ∈ (PAC, IAC, HC, EC, DC, PC)",
        used_for = Purpose.cadence_induction,
    ),
    phraseend = dict(
        description = "Original phrase labels.",
        used_for = Purpose.auxiliary,
    ),
    is_phrase_ending = dict(
        description = "True for notes that coincide with the structural ending of a phrase (i.e., the phrase can have "
                      "a codetta after this position before the next one begins).",
        used_for = Purpose.phrase_inference,
    ),
    unfolded_harmony_index = dict(
        description = "Index of the labels in the original unfolded table (before merging it with the notes)",
        used_for = Purpose.auxiliary,
    ),
    label = dict(
        description = "Original annotation labels",
        used_for = Purpose.auxiliary,
    ),
    globalkey_tpc = dict(
        description = f"Root of the global key expressed as {tpc_description}",
        used_for = Purpose.auxiliary,
    ),
    localkey_tpc = dict(
        description = f"Root of the local key expressed as {tpc_description}",
        used_for = Purpose.auxiliary,
    ),
    tonicized_tpc = dict(
        description = f"Root of the tonicized key expressed as {tpc_description}",
        used_for = Purpose.auxiliary,
    ),
    sic_with_local = dict(
        description = "Relative position of the note's tonal pitch class in the local key, expressed as "
                      "Specific Interval Class (0=unison, -1=+P4/-P5, 3=+M6/-m3, etc.)",
        used_for = Purpose.auxiliary,
    ),
    tpc_is_in_label = dict(
        description = "True if a note's pitch class is part of the harmony label",
        used_for = Purpose.harmony_inference,
    ),
    tpc_is_root = dict(
        description = "True if a note's tonal pitch class is the harmony label's root",
        used_for = Purpose.harmony_inference,
    ),
    tpc_is_bass = dict(
        description = "True if a note's tonal pitch class is the harmony label's bass",
        used_for = Purpose.harmony_inference,
    ),
)

specs = labeled_pitch_array.dtypes.rename("dtype")
specs_df = pd.concat([
    specs,
    pd.DataFrame.from_dict(spec_specs, orient="index")
], axis=1)[["dtype", "used_for", "description"]]
specs_df.to_csv("labeld_pitch_array_specs.csv", index=True)
specs_df

,dtype,used_for,description
onset_div,int64,Purpose.input,Proportional integer position
duration_div,int64,Purpose.input,Proportional integer duration
pitch,Int64,Purpose.input,MIDI value
tpc,Int64,Purpose.auxiliary,"Tonal Pitch Class (0=C, -1=F, 1=G, etc., aka s..."
step,object,Purpose.input,Note name without accidental (A-G)
...,...,...,...
sic_with_local,Int64,Purpose.auxiliary,Relative position of the note's tonal pitch cl...
sic_with_tonicized,Int64,NaN,NaN
tpc_is_in_label,boolean,Purpose.harmony_inference,True if a note's pitch class is part of the ha...
tpc_is_root,boolean,Purpose.harmony_inference,True if a note's tonal pitch class is the harm...
tpc_is_bass,boolean,Purpose.harmony_inference,True if a note's tonal pitch class is the harm...